# Generated by Django 5.0.1 on 2024-01-21 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('customerEmail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Customer service request',
                'verbose_name_plural': 'Customer service requests',
            },
        ),
        migrations.DeleteModel(
            name='Careers',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'reservation', 'verbose_name_plural': 'reservations'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AddField(
            model_name='book',
            name='bookingTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='book',
            name='phone',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='', upload_to='restaurantApp/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='isPopular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookingDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isSpecialEvent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_guests',
            field=models.IntegerField(default=2),
        ),
    ]
