# Generated by Django 5.0.1 on 2024-01-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0002_contactus_delete_careers_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
