# Generated by Django 5.0.1 on 2024-01-22 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='isPopular',
        ),
    ]
