# Generated by Django 5.0.1 on 2024-01-22 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0002_remove_menu_ispopular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
    ]
