# Generated by Django 5.0.1 on 2024-01-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0003_remove_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='', upload_to='restaurantApp/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='isPopular',
            field=models.BooleanField(default=False),
        ),
    ]
