# Generated by Django 5.0.1 on 2024-01-22 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0004_menu_image_menu_ispopular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='phone',
        ),
    ]
