# Generated by Django 5.0.1 on 2024-01-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0005_remove_book_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='phone',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
