# Generated by Django 5.0.1 on 2024-01-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0006_book_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
