# Generated by Django 5.0.1 on 2024-01-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0007_alter_book_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
