# Generated by Django 5.0.1 on 2024-01-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0009_alter_menu_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='isPopular',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
    ]
