# Generated by Django 5.0.1 on 2024-01-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0010_remove_menu_image_remove_menu_ispopular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='', upload_to='restaurantApp/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='isPopular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
