# Generated by Django 5.0.1 on 2024-01-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0011_menu_image_menu_ispopular_menu_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
    ]
