# Generated by Django 5.0.1 on 2024-01-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0013_menu_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu_Item', 'verbose_name_plural': 'Menu_Items'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='', upload_to='meals/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', null=True, unique=True),
        ),
    ]
