# Generated by Django 5.0.1 on 2024-01-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0014_alter_menu_options_alter_menu_image_alter_menu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
