# Generated by Django 5.0.2 on 2024-02-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0016_menu_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isSpecialEvent',
            new_name='isConfirmed',
        ),
    ]
