# Generated by Django 5.0.2 on 2024-02-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0017_rename_isspecialevent_book_isconfirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
