# Generated by Django 5.0.2 on 2024-02-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0018_contactus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='isResolved',
            field=models.BooleanField(default=False),
        ),
    ]
